### ISSUE TITLE
fail if start from terminal

### ISSUE THREAD

**Issue by Red-Eyed** [flathub/org.gnome.meld#21] opened 2020-04-01 12:38 UTC
I use the latest Manjaro Gnome with lts kernel.
I have issue with starting meld from the terminal

```
flatpak run org.gnome.meld
Traceback (most recent call last):
  File "/app/bin/meld", line 79, in <module>
    import meld.conf  # noqa: E402
ModuleNotFoundError: No module named 'meld'
```

But I can run meld via Gnome Launcher (or how is that menu called when I press super button ?)
And yes, I'm sure that I run meld from flatpak

**Comment by bilelmoussaoui** [comment] 2020-04-01 12:42
That seems like an upstream issue.

**Comment by Red-Eyed** [comment] 2020-04-01 12:43
Oh, thanks for the quick reply!

I wonder, why does it work from gnome launcher and doesn't with direct command?

**Comment by TingPing** [comment] 2020-04-01 14:11
I can't reproduce here. Maybe you have some problematic env var set, whats the output of `env`?

**Comment by Red-Eyed** [comment] 2020-04-01 15:39
Oh, I've got it.
The problem is that I set by default `PYTHONNOUSERSITE=1` in my `.zshrc` file
When I set it to 0 - it works fine then.

But I wonder, I thought that sandboxed apps don't depend on system env.

Should we treat it as a bug?

**Comment by TingPing** [comment] 2020-04-01 15:59
I would call it a bug yes. Could you report it against https://github.com/flatpak/flatpak that `PYTHONNOUSERSITE` shouldn't make it into the sandbox.

**Comment by TingPing** [comment] 2020-04-01 16:01
Actually this may also be a freedesktop-sdk bug. Why does `/app/...` count as a user site?.. That should be discussed https://gitlab.com/freedesktop-sdk/freedesktop-sdk/

**Comment by Red-Eyed** [comment] 2020-04-01 16:02
Yes, I can.
But there is lot of ENV variables that python use, and other programs use another ENV vars.
So, actually flatpak shouldn't pass any vars into sandbox

**Comment by TingPing** [comment] 2020-04-01 16:04
There is a balance to be had. Flatpak wants to integrate with the host system when possible but not conflict with it. I agree it should err on the side of blocking though.

**Comment by Red-Eyed** [comment] 2020-04-01 16:05
So, maybe the flatpak application itself should decide, which vars it can take from host?
Like, creators of meld package in flatpak can block any host vars that can affect runtime

**Comment by Red-Eyed** [comment] 2020-04-01 16:06
For example, it's a well know practice for python to make `isolated virtual envs`

**Comment by TingPing** [comment] 2020-04-01 16:09
I reported the sdk issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/997

**Comment by Red-Eyed** [comment] 2020-04-01 16:11
Thanks for reporting!
Also, maybe mentioning this issue make sense and would help?

**Comment by Red-Eyed** [comment] 2020-04-01 16:12
So, is it going to `won't fix` then?

**Comment by TingPing** [comment] 2020-04-01 16:13
Done.

> So, maybe the flatpak application itself should decide, which vars it can take from the host?

So the application can already *kinda* do that, either via `--env=...` permissions or via a wrapper script.

This however is a broad enough problem that I think `flatpak` should handle it.

> So, is it going to won't fix then?

I don't think package should work around it. You can do this until it is fixed in the sdk: `flatpak override --user org.gnome.meld --env=PYTHONNOUSERSITE=0`.

**Comment by Red-Eyed** [comment] 2020-04-01 16:15
Oh, thanks!
Will use it in my `.gitconfig`

**Closed** 2020-04-01 16:21 UTC

**Comment by TingPing** [comment] 2020-04-01 16:24
The override command persists, only need to set it once.

**Comment by Red-Eyed** [comment] 2020-04-01 16:25
Yeah, I know it, thanks.
