### ISSUE TITLE
Version control compare "git not installed"

### ISSUE THREAD

**Issue by Sarke** [flathub/org.gnome.meld#16] opened 2019-07-19 23:21 UTC
If I select "Version Control View", it will give me a dropdown on the right that has two entries:

- None
- Git (git not installed)

Can we add git to this package?

**Comment by p1u3o** [comment] 2019-08-05 09:38
This is because org.gnome.Platform doesn't have Git where as org.gnome.Sdk does.

Could always switch Meld to using the SDK as it's runtime.

**Comment by redefinitionof** [comment] 2019-08-16 14:21
I think I have the same issue as TS. I am trying to compare the differences at my working directory and my local changes in a GitHub project. I see the same menu as TS and no differences are processed in the main window (only see root folder).

If the issue is the same, I don't understand how to apply the fix from p1u3o. Where to enter this command? My windows cmd-terminal does not recognize flatpak.

**Comment by Sarke** [comment] 2019-09-14 00:48
@p1u3o Thanks :+1: 

@redefinitionof Do you have flatpak install?  If not, you probably installed meld some other way.  Just install git.

If you do, install the runtime like this:
`flatpak install flathub org.gnome.Sdk//3.34`

Then run meld like this:
`flatpak run --runtime=org.gnome.Sdk//3.34 org.gnome.meld`

**Comment by TingPing** [comment] 2019-09-14 00:51
It should probably include git..

**Comment by bilelmoussaoui** [comment] 2020-01-23 12:36
Should be fixed.

**Closed by bilelmoussaoui** 2020-01-23 12:36 UTC
